name: Chris Paltzat Photography
favicon: null
layout_spectrum: 0.5204939355608076
typography_spectrum: 0.60157
title: Chris Paltzat Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#36638a'
    - '#98b3ce'
    - '#050908'
    - '#fcfcfc'
    - '#5c3f00'
  brandStrength: 0.1111213902477175
  lightness: 0.5661648686509579
  saturation: 0.9334019394591451
  rhythmicContrast: 0.2745582575444132
purpose: []
